.TH KNAVALBATTLE 6
.SH NAME
knavalbattle \- The KDE Battleship clone
.SH SYNOPSIS
.B knavalbattle
.I [Qt-options] [KDE-options] [url]
.SH DESCRIPTION
.B knavalbattle
is a network-enabled implementation of the famous `Battle Ship' game
for KDE.
.TP
.B url
URL of a Naval Battle game server to connect to after startup
.so kdeopt.part
.SH SEE ALSO
More detailed user documentation is available from
.BR help:/kbattleship
(either enter this URL into \fBkonqueror\fP, or run `khelpcenter
help:/knavalbattle).
